/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsUsageRouteImport } from './routes/docs/usage'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsHowItWorksRouteImport } from './routes/docs/how-it-works'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DocsUsageRoute = DocsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/usage': typeof DocsUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/usage': typeof DocsUsageRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/usage': typeof DocsUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/docs/configuration'
    | '/docs/how-it-works'
    | '/docs/installation'
    | '/docs/usage'
    | '/dashboard/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/configuration'
    | '/docs/how-it-works'
    | '/docs/installation'
    | '/docs/usage'
    | '/dashboard'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/docs/configuration'
    | '/docs/how-it-works'
    | '/docs/installation'
    | '/docs/usage'
    | '/dashboard/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/docs/usage': {
      id: '/docs/usage'
      path: '/usage'
      fullPath: '/docs/usage'
      preLoaderRoute: typeof DocsUsageRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsUsageRoute: typeof DocsUsageRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsUsageRoute: DocsUsageRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
